# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intakedata',
            name='id',
        ),
        migrations.AlterField(
            model_name='intakedata',
            name='name',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
