# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190116_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.intakedata')),
            ],
        ),
    ]
