# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='comp_name',
        ),
        migrations.DeleteModel(
            name='company',
        ),
    ]
