# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190116_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='candid_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='question',
            name='email_id',
            field=models.EmailField(default='5', max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
