# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190118_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='candid_name',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='age',
        ),
        migrations.RemoveField(
            model_name='question',
            name='email_id',
        ),
    ]
